// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzqsijxitpydpmtjybzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6cXNpanhpdHB5ZHBtdGp5Ynp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjczMjMsImV4cCI6MjA2NTU0MzMyM30.820LQ2objLubyOMTbg3yQeOW3CwNkpdSJ_NNXMWu9Lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);